#ifndef HELLO_WORLD_PLUGIN_GLOBAL_H
#define HELLO_WORLD_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QDebug>

#if defined(HELLO_WORLD_PLUGIN_LIBRARY)
#  define HELLO_WORLD_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HELLO_WORLD_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HELLO_WORLD_PLUGIN_GLOBAL_H
